name: Deploy Infrastructure
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Apply on Proxmox
    runs-on: self-hosted

    steps:
      - name: Git Pull latest changes
        run: |
          cd /home/terraform/Terraform/Projets/Terraform
          git pull https://${{ secrets.TOKEN_GITHUB }}@github.com/ArcElewyn/Terraform.git main

      - name: Terraform Init
        run: | 
          cd /home/terraform/Terraform/Projets/Terraform/Provisioning
          terraform init

      - name: Terraform Plan
        run: |
          cd /home/terraform/Terraform/Projets/Terraform/Provisioning
          terraform plan \
            -var="proxmox_url=${{ secrets.PROXMOX_URL }}" \
            -var="proxmox_token=${{ secrets.PROXMOX_TOKEN }}" \
            -var="proxmox_user=${{ secrets.PROXMOX_USER }}" \
            -var="cloudinit_sshkey=${{ secrets.CLOUDINIT_SSHKEY }}" \
            -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: |
          cd /home/terraform/Terraform/Projets/Terraform/Provisioning
          terraform apply -auto-approve \
            -var="proxmox_url=${{ secrets.PROXMOX_URL }}" \
            -var="proxmox_token=${{ secrets.PROXMOX_TOKEN }}" \
            -var="proxmox_user=${{ secrets.PROXMOX_USER }}" \
            -var="cloudinit_sshkey=${{ secrets.CLOUDINIT_SSHKEY }}" \
            -var-file="terraform.tfvars"
