- name: Create prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"
    - "{{ prometheus_tmp_dir }}"

- name: Download Prometheus archive
  get_url:
    url: "{{ prometheus_url }}"
    dest: "{{ prometheus_tmp_dir }}/{{ prometheus_package }}.tar.gz"
    mode: '0644'

- name: Extract Prometheus
  unarchive:
    src: "{{ prometheus_tmp_dir }}/{{ prometheus_package }}.tar.gz"
    dest: "{{ prometheus_tmp_dir }}/"
    remote_src: yes

- name: Move binaries
  copy:
    remote_src: yes
    src: "{{ prometheus_tmp_dir }}/{{ prometheus_package }}/prometheus"
    dest: "{{ prometheus_install_dir }}/prometheus"
    mode: '0755'

- name: Move promtool
  copy:
    remote_src: yes
    src: "{{ prometheus_tmp_dir }}/{{ prometheus_package }}/promtool"
    dest: "{{ prometheus_install_dir }}/promtool"
    mode: '0755'

- name: Copy consoles & console_libraries
  copy:
    remote_src: yes
    src: "{{ prometheus_tmp_dir }}/{{ prometheus_package }}/{{ item }}"
    dest: "{{ prometheus_config_dir }}/{{ item }}"
  loop:
    - consoles
    - console_libraries

- name: Deploy prometheus.yml config
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Copy systemd service file for prometheus agent
  copy:
    src: prometheus-agent.service
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started

- name: Clean temporary files
  file:
    path: "{{ prometheus_tmp_dir }}"
    state: absent
