---
- name: "Create user {{ user_name }}"
  user:
    name: "{{ user_name }}"
    shell: /usr/sbin/nologin
    system: yes
    create_home: no

- name: " Create directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'
  loop:
    - "{{ working_directory }}"
    - "{{ log_directory }}"
    - "{{ conf_directory }}"

- name: "Deploy template to systemd {{ service_name }}.service"
  template:
    src: template.service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: '0644'

- name: Enable and start the service
  ansible.builtin.systemd_service:
    name: {{ service_name }}
    state: started
    enabled: true
...